package madson.org.opentournament.events;

/**
 * Write some fancy Javadoc!
 *
 * @author  Tobias Matt - tmatt@contargo.net
 */

public enum OpenTournamentEventTag {

    TOURNAMENT_STARTED,
    NEXT_ROUND_PAIRED,
    SWAP_PLAYER,
    PAIR_ROUND_AGAIN,
    ADD_REGISTRATION,
    UPDATE_TOURNAMENT_PLAYER,
    REMOVE_TOURNAMENT_PLAYER,
    ADD_TOURNAMENT_PLAYER,
    REMOVE_AVAILABLE_PLAYER,
    SAVE_GAME_RESULT_CONFIRMED,
    PAIRING_CHANGED,
    UPDATE_TOURNAMENT,
    ADD_TOURNAMENT,
    DELETE_TOURNAMENT,
    END_SWAP_PLAYER,
    DELETE_LOCAL_PLAYER,
    UNDO_ROUND,
    UNDO_TOURNAMENT_ENDING;
}
